export enum ErrorCode {
	COMPANY_ALREADY_EXISTS_ERROR = "COMPANY_ALREADY_EXISTS_ERROR",
	WRONG_CREDENTIALS_ERROR = "WRONG_CREDENTIALS_ERROR",
	PASSWORDS_DOES_NOT_MATCH_ERROR = "PASSWORDS_DOES_NOT_MATCH_ERROR",
	INVALID_EMAIL_ERROR = "INVALID_EMAIL_ERROR",
	INVALID_PASSWORD_ERROR = "INVALID_PASSWORD_ERROR",
}
