export enum DomainCode {
	RESOURCE_ALREADY_EXISTS_ERROR = "RESOURCE_ALREADY_EXISTS_ERROR",
	RESOURCE_NOT_FOUND_ERROR = "RESOURCE_NOT_FOUND_ERROR",
	INVALID_ROLE_ERROR = "INVALID_ROLE_ERROR",
	NOT_ALLOWED_ERROR = "NOT_ALLOWED_ERROR",
	BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR",
}
